server:
  port: 8999
  session:
    cookie:
      name: UISESSION
  servlet:
    context-path: /v1
spring:
  thymeleaf:
    cache: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/aimeeTest2

oauth:
  token:
    callback: http://192.168.1.103:8080

# jwt 配置
custom:
  jwt:
    # header:凭证(校验的变量名)
    header: Authorization
    # 有效期1天(单位:s)
    expire: 5184000
    # secret: 秘钥(普通字符串) 不能太短，太短可能会导致报错
    secret: 99c2918fe19d30bce25abfac8a3733ec
    # 签发者
    issuer: luo

jjwt:
  key: aXNsZWVfaGFoYQ==


